### ISSUE TITLE
grids for IFS output

### ISSUE THREAD

**Issue by klauswyser** [goord/ece2cmor3#24]
The netCDF files at the end of the cmorisation process include information about the grid. The fields from IFS are saved on a regular Gauss grid. and the netCDF file contains information about grid centers as well as grid corners (vertices).

A few issues with the grid need more attention:
* *Orientation* are currently N-S and W-E(!). Is that correct? For CMIP6 the orientation was S-N and E-W.
* *Vertices* are numbered counter-clockwise, correct?
* *vertices_longitude* have gaps. Here is the top-left corner of the grid (from a T255 experiment):

> octave:32> squeeze(vertices_longitude(1,1:3,1:3))
> ans =
>    358.24   356.84   355.43
>    358.24   356.84   355.43
>    358.24   356.84   355.43
> 
> octave:33> squeeze(vertices_longitude(2,1:3,1:3))
> ans =
>    358.95   357.54   356.13
>    358.95   357.54   356.13
>    358.95   357.54   356.13

The first index loops over the vertices. We would expect the 1st corner of the first gripdoint to be identical to the 2nd corner of the next gridpoint, but apparently there is a gap.

**Comment by goord** [comment]
Hi Klaus, I haven't noticed this, but I suspect that this is incorrect. I will have a look at the grid definition.

**Comment by goord** [comment]
Hi Klaus, the orientation is based upon the cdo griddes result, which apparently gives the latitudes in descending order. This leads also to a somewhat counterintuitive descending j-index axis. If this orientation is nonstandard, I propose to change it to SN-EW

**Comment by klauswyser** [comment]
The orientation is "wrong" in the IFS output that starts at the North Pole and ends at the South Pole. For CMIP5 we had to add `-invertlat` to the cdo processing to get the proper SN orientation that was requested.

But, as said before, I don't know the specs for CMIP6, it may be OK to have the latitudes in NS orientation.

**Comment by goord** [comment]
If nothing is mentioned in the spec document, I guess it is the same as CMIP5. I also noticed that the latitude and longitude dimensions in the final netcdf files have been swapped, which is definitely a bug (the ordering of i and j may be somewhat arbitrary).

**Comment by goord** [comment]
Commit nr d709240349e5e565d8052934e9c1ec57a90251d1

**Comment by klauswyser** [comment]
Longitudes and latitudes are switched now, does this make sense? When I look at a netCDF file I have to turn my head 90 degrees... I thought it should be the other way round.

Orientation is now EW-NS. Is NS OK with CMIP6? It wasn't with CMIP5, but there may be no specs for CMIP6.

The latitude of the top and bottom grid corners is not correct:
```
octave:16> squeeze(vertices_latitude(1,1:3,1:3))
ans =
  -90.000  -90.000  -90.000
   89.115   89.115   89.115
   88.417   88.417   88.417
```

The longitude of the grid corners looks OK now, although the last longitudes are
```
octave:22> squeeze(x(2,end-2:end,end-2:end))
ans =
   358.59375   359.29688     0.00000
   358.59375   359.29688     0.00000
   358.59375   359.29688     0.00000
```
Correct in principle, but wouldn't it be nicer to have 360 instead of 0? Or is `mod 360` automatically applied by the CMOR3 library?

**Comment by goord** [comment]
Hi Klaus, I think I fixed it in the latest commit.

**Comment by klauswyser** [comment]
No, I don't think so. I have updated ece2cmor3 and rerun my example, yet still see the problems mentioned above.

With this command:
```
ncdump cmor/CMIP/EC-Earth-Consortium/EC-Earth-3-HR/historical/r1i1p1f1/Amon/tas/gr/v20170504/tas_Amon_historical_EC-Earth-3-HR_r1i1p1f1_gr_199001-199001.nc -v vertices_latitude | more
```
I get 
```
[...]
 vertices_latitude =
  -90, -90, 89.11488, 89.11488,
  89.11488, 89.11488, 88.41696, 88.41696,
  88.41696, 88.41696, 87.71651, 87.71651,
[...]
```
Doesn't look good!

**Comment by goord** [comment]
This is very strange, they start at 90 on my system...

**Comment by klauswyser** [comment]
Sorry, my fault. My ece2cmor3 tool was not properly updated, now things look fine. Closing the issue.
